apiVersion: v1
kind: ConfigMap
metadata:
  name: ssh-keys-config
  namespace: kube-system
data:
  authorized_keys: |
    ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDrgCEe+Lw4PzqWVmoEwpbLo1mZijGqE6/V3RFDTF+ng3Uahlcuip99ccMLOhoKl8MVrylAtgc5Qv41xoGLQfhCFnLVkvLF2EhEPEdJ+XSH1le2kbMF6Ycf553l1cg8IyZnMdEBeQYtBrucnObpVzVrAz/yrn/PlADrg6s+b0mKDFCa5NfYqSuElJ1KQ5JsOUugsx+ztbY2PLjHwvOrDQ4QMEEamgaAw3pNsNRptdqt2ZmWUzk+q6yIM96GIFUjJqYnPkEHgn1Vlsr76Brl7j/bY9GV2E4qirXOa3AyhyqpTCZBMEJt0G3NmXKnuCoB5wmqKJ+zp8wyL6AFPQTnd/9OsQfelODEe/ngt4g4X67o7gfHcj756K051TEyTF/4wbURqM94xclDrlNpUWy1PUXaE3Bv6Ia0exhPbg+U4hi/VSTBEAhXxufO9X4yqtpCBlzzL1ODiSQaNfefSRr9lxidyg3zPDNWrhT4AoFbYa0e9RcDDkcu406mLVSyZOo0x88= Chatresh-hash
    # You can add multiple keys here, one per line
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ssh-key-injector
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: ssh-key-injector
  template:
    metadata:
      labels:
        name: ssh-key-injector
    spec:
      hostPID: true
      hostNetwork: true
      containers:
      - name: ssh-key-injector
        image: busybox:latest
        command:
        - sh
        - -c
        - |
          cat /config/authorized_keys >> /hosthome/opc/.ssh/authorized_keys
        volumeMounts:
        - name: hosthome
          mountPath: /hosthome
        - name: sshkeys
          mountPath: /config
      volumes:
      - name: hosthome
        hostPath:
          path: /home
      - name: sshkeys
        configMap:
          name: ssh-keys-config
      restartPolicy: Always
